### ISSUE TITLE
Help with installation error

### ISSUE THREAD

**Issue by nyoman1994** [slevyrosetti/ivim-toolbox#1]
Dear Dr Levy,
I tried to install your program but I run into this problem. 
Would you help to fix this error?

Thanks,
Nyoman

Traceback (most recent call last):
  File "/Users/xx/ivim-toolbox-master/./ivim_toolbox.py", line 249, in <module>
    frameRequiredSNR = FrameRequiredSNR(parent=None, title='IVIM toolbox: compute required SNR')
  File "/Users/uqnkurn1/ivim-toolbox-master/./ivim_toolbox.py", line 99, in __init__
    hbox1.Add(l1, 1, wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 5)
wx._core.wxAssertionError: C++ assertion "CheckSizerFlags(!((flags) & (wxALIGN_RIGHT | wxALIGN_CENTRE_HORIZONTAL | wxALIGN_BOTTOM | wxALIGN_CENTRE_VERTICAL)))" failed at /Users/robind/projects/bb2/dist-osx-py39/build/ext/wxWidgets/src/common/sizer.cpp(2294) in DoInsert(): wxALIGN_RIGHT | wxALIGN_CENTRE_HORIZONTAL | wxALIGN_BOTTOM | wxALIGN_CENTRE_VERTICAL will be ignored in this sizer: wxEXPAND overrides alignment flags in box sizers

DO NOT PANIC !!

If you're an end user running a program not developed by you, please ignore this message, it is harmless, and please try reporting the problem to the program developers.

You may also set WXSUPPRESS_SIZER_FLAGS_CHECK environment variable to suppress all such checks when running this program.

If you're the developer, simply remove this flag from your code to avoid getting this message. You can also call wxSizerFlags::DisableConsistencyChecks() to globally disable all such checks, but this is strongly not recommended.

**Comment by sarahrmorris** [comment]
Hi Nyoman, 

I am also getting this same error! Did you ever find a fix?

Thanks, Sarah

**Comment by nyoman1994** [comment]
Hi Sarah,
No, I didn’t find.

Regards, Nyoman


From: Sarah Morris ***@***.***>
Date: Thursday, 21 March 2024 at 7:02 AM
To: slevyrosetti/ivim-toolbox ***@***.***>
Cc: Nyoman Kurniawan ***@***.***>, Author ***@***.***>
Subject: Re: [slevyrosetti/ivim-toolbox] Help with installation error (Issue #1)

Hi Nyoman,

I am also getting this same error! Did you ever find a fix?

Thanks, Sarah

**Comment by slevyrosetti** [comment]
Hi Nyoman and Sarah,

Sorry @nyoman1994 for not noticing this issue, and many thanks @sarahrmorris for bringing it to my attention.

This issue happens with the Graphical User Interface I implemented to be able to visualize the fit voxel-by-voxel based on the resulting IVIM map when clicking on the voxel of interest. This was a little experimental but was working well at the time I was actively working on the toolbox. The other functionalities of the toolbox should still work without issue.

It does not look like it is related to the Python code but to a library used or a write/read issue. Note that the fitting of the data needs to be performed before using this function and the plots of the fit within each voxel need to be saved before using this function such that they can be loaded when you want to visualize the fits voxel-by-voxel.

Maybe if you could first tell me the command line you are trying to run I could guide you to find the cause of the issue.

Let me know how you go.
Thanks,
Simon

**Comment by slevyrosetti** [comment]
Hi all,

It seems like running the toolbox on Windows with the multi-threading option activated can cause some issues. Could you let me know which OS are you using the toolbox with?

If you are using Windows, would you be able to try running the same command with multi-threading turned off and let me know if it solves your issue? To do so, you just need to change `self.MTCheckBox.SetValue(True)` at line 48 of the file [ivim_toolbox.py](https://github.com/slevyrosetti/ivim-toolbox/blob/master/ivim_toolbox.py) into `self.MTCheckBox.SetValue(False)`.

Please let me know how you go.

Kind regards,
Simon

**Comment by nyoman1994** [comment]
Hi Simon,
I have not tried this for a while now. I just tried to compile again last week using MacOs 14.5 (M1 CPU) but I can’t get it to work.
I think cPickle is no longer available.

Regards,
Nyoman




On 14 Jun 2024, at 12:09 AM, Simon Lévy ***@***.***> wrote:



Hi all,

It seems like running the toolbox on Windows with the multi-threading option activated can cause some issues. Could you let me know which OS are you using the toolbox with?

If you are using Windows, would you be able to try running the same command with multi-threading turned off and let me know if it solves your issue? To do so, you just need to change self.MTCheckBox.SetValue(True) at line 48 of the file ivim_toolbox.py<https://github.com/slevyrosetti/ivim-toolbox/blob/master/ivim_toolbox.py> into self.MTCheckBox.SetValue(False).

Please let me know how you go.

Kind regards,
Simon

**Comment by slevyrosetti** [comment]
Hi Nyoman,

What Python version are you using and what error do you get (if still the same as in the first message of this thread, what is the error with multi-threading turned off)?

cPickle is a Python 2.x specific package, the C accelerator has been included in the standard library for Python 3. If your are using Python 3 (which I did not test the toolbox with) and if cPickle is the problem, just replace the lines `import _pickle as pickle` by `import pickle` as explained [here](https://stackoverflow.com/questions/56562929/modulenotfounderror-no-module-named-cpickle-on-python-3-7-3/56563226#56563226) or [here](https://stackoverflow.com/questions/49579282/cant-find-module-cpickle-using-python-3-5-and-anaconda).

Or just try to use Python 2.

Let me know if that fixes your problem.

Kind regards,
Simon
