### ISSUE TITLE
Error: NameError: name 'approach' is not defined

### ISSUE THREAD

**Issue by ampaschoal** [slevyrosetti/ivim-toolbox#3]
Hi,

I'm trying to run the ivim_fitting but I'm facing the following error. Does anyone know how to fix it?

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ~~~~^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/Users/ampaschoal/ivim-toolbox-master/ivim_fitting.py", line 1060, in fit_warpper
    if approach == '1pool_separate':
       ^^^^^^^^
NameError: name 'approach' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ampaschoal/ivim-toolbox-master/ivim_fitting.py", line 1111, in <module>
    main(dwi_fname=args.dwi_fname, bval_fname=args.bval_fname, mask_fname=args.mask_fname, model=args.model, ofolder=args.ofolder, multithreading=bool(int(args.multithreading)))
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ampaschoal/ivim-toolbox-master/ivim_fitting.py", line 112, in main
    ivim_fit.run_fit()
    ~~~~~~~~~~~~~~~~^^
  File "/Users/ampaschoal/ivim-toolbox-master/ivim_fitting.py", line 75, in run_fit
    self.ivim_metrics_all_voxels = pool.map(fit_warpper, fit_func_args)
                                   ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/multiprocessing/pool.py", line 774, in get
    raise self._value
NameError: name 'approach' is not defined

**Comment by slevyrosetti** [comment]
Hi Andre @ampaschoal ,

Apologies as I missed your message. I am sorry you encountered this issue. Were you able to find the cause? If not, could you tell us a bit more about the command or process you used to run the script and which led to this error?
Did you use a command line similar to this one?
`ivim_fitting.py -i dwi.nii.gz -b bval.txt -ma mask.nii.gz -mo one-step -o ivim_maps -mt 1 `

If so, it could be due to the multithreading. Try this command line (turning off the multithreading) instead to see if this is the problem:
`ivim_fitting.py -i dwi.nii.gz -b bval.txt -ma mask.nii.gz -mo one-step -o ivim_maps -mt 0 `

Let me know how you go.

Cheers,
Simon
